apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
      release: v1
  template:
    metadata:
      labels:
        app: demo-app
        release: v1
    spec:
      containers:
      - name: nginx
        image: europe-west4-docker.pkg.dev/kubernetes-week1/maurice535961rp/webserver:blue
        ports:
        - containerPort: 80
