# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  labels:
    app: demo-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
      version: green
  template:
    metadata:
      labels:
        app: demo-app
        version: green
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/PROJECT_ID/container-example/app-image:GREEN_VERSION
        ports:
        - containerPort: 80


