apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: ClusterIP
  selector:
    app: website
    version: v1  # Hier specificeer je welke versie je wilt gebruiken
  ports:
    - port: 80
      targetPort: 80


