# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: demo-app
    version: blue  # Initieel wijst dit naar de blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer


