apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: LoadBalancer
  selector:
    app: webserver
    version: blue  # Dit label bepaalt of je naar blue of green verwijst
  ports:
    - port: 80
      targetPort: 80
