name: Build, Push to Artifact Registry, and Deploy to GKE

on:
  push:
    branches: ["main", "test"]

env:
  PROJECT_ID: kubernetes-week1
  REGION: europe-west4
  REPOSITORY: maurice535961rp
  CLUSTER_NAME: autopilot-cluster-1
  ZONE: us-central1

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        
      - name: "Docker auth"
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev
        
      - name: "Get branch name"
        id: branch-name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        
      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v2"
        with:
          push: true
          tags: |
            europe-west4-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/webserver:${{ steps.branch-name.outputs.branch == 'main' && 'blue' || 'green' }}
            
      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.ZONE }}
          project_id: ${{ env.PROJECT_ID }}
          
      - name: "Deploy to GKE"
        run: |
          kubectl apply -f Week3/week3deploymentblue.yaml
          kubectl apply -f Week3/week3deploymentgreen.yaml
          kubectl rollout status deployment/demo-app-${{ steps.branch-name.outputs.branch == 'main' && 'blue' || 'green' }}
